[project]
name = "third-party"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.agreement]
path = "contracts/agreement.clar"
depends_on = []
